### ISSUE TITLE
calico-2014.1.4/2.2 branches have broken DHCP agent

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-neutron#9]
The DHCP agent on calico-2014.1.4/2.2 falls on its face due to an argument mismatch:

```
TypeError: init_l3() takes at most 5 arguments (7 given)
```

**Comment by nelljerram** [comment]
Exactly what code are you seeing this with?  I believe I fixed this last week in https://github.com/Metaswitch/calico-neutron/commit/c4c0274b7fba7f9d315a0dec6a062bf91ad82ba6, before making the 0.18 release.

Is it perhaps that you need to cherry-pick that commit into https://github.com/Metaswitch/calico-neutron/tree/smc-calico_2014.1.4-dhcp-optimize ?

**Comment by fasaxc** [comment]
Yep, that looks like it does it.  I've rebased my branch.  Looks like it was only 1.4 that was having issues.  I was confused.
